miami: Add soong namespace
Fixes:

FAILED: out/soong/build.lineage_miami.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out
"out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_miami.variables -o out/soong/build.lineage_miami.ninja --globListDir lineage_miami --globFile out/soong/globs
-lineage_miami.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_miami.build Android
.bp
error: kernel/motorola/sm6375/Android.bp:134:1: module "qti_kernel_headers" already defined
       vendor/lineage/build/soong/Android.bp:58:1 <-- previous definition here
fatal errors encountered
08:23:21 soong bootstrap failed with: exit status 1

Signed-off-by: betaxab <betaxab@gmail.com>
(cherry picked from commit 77474e9dfc25406b81e3a5a4e8a71df8cecfbb9b github.com/moto-common/android_kernel_motorola_msm-5.4)
Signed-off-by: Juerg Haefliger <juergh@proton.me>